version: '3.8'

networks:
  app-tier:
    name: app-tier
    driver: bridge

services:

  web: #fastapi server
    container_name: api-web
    build:
      context: .
      dockerfile: ./dockerfile
    image: example_fastapi
    command: ["sh", "-c", "./entrypoint.sh api"]
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    env_file:
      - config/dev.env
    depends_on:
      - rabbitmq
    expose:
      - '8080'
    networks:
      - app-tier

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.11.3-management
    ports:
      # port for workers
      - "5672:5672"
      # gui port
      - "15672:15672"
    restart: on-failure
    networks:
      - app-tier

  celery_worker: # Celery worker process
    container_name: celery_worker
    build:
      context: .
      dockerfile: ./dockerfile
    image: example_celery_worker
    command: ["sh", "-c", "./entrypoint.sh worker"]
    volumes:
      - ./app:/app
    env_file:
      - config/dev.env
    depends_on:
      - rabbitmq
    networks:
      - app-tier

  celery_flower: #Celery dashboard
    container_name: celery_flower
    build:
      context: .
      dockerfile: ./dockerfile
    image: example_celery_flower
    command: ["sh", "-c", "./entrypoint.sh flower"]
    volumes:
      - ./app:/app
    env_file:
      - config/dev.env
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq
    networks:
      - app-tier


